# Generated by Django 5.0.9 on 2024-11-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=10)),
                ('original_publication_year', models.DateField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_count', models.IntegerField()),
                ('small_image_url', models.TextField()),
            ],
        ),
    ]
