# Generated by Django 5.0.9 on 2024-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('language_code', models.CharField(max_length=10)),
                ('original_publication_year', models.IntegerField(default=0)),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('small_image_url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
