# Generated by Django 5.0.9 on 2024-11-18 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ratings_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.CharField(max_length=1000)),
                ('language_code', models.CharField(max_length=10)),
                ('original_publication_year', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('small_image_url', models.URLField()),
                ('image_url', models.URLField()),
                ('statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webooks.bookstatistics')),
            ],
        ),
    ]
