# Generated by Django 5.0.9 on 2024-11-24 12:14

import django.core.validators
from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    with open('webooks/migrations/book.csv', 'r', encoding='utf8') as all_books_file:
        reader = csv.DictReader(all_books_file, delimiter=',')

        for row in reader:
            statistics = BookStatistics(average_rating=row['average_rating'], ratings_count=row['ratings_count'])
            statistics.save()

class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ('webooks', '0005_alter_book_original_publication_year'),
    ]
